package homebasedesktop;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import homebasedesktop.entity.*;
import javax.persistence.*;
import javax.swing.Timer;
import java.util.*;
import java.io.File;
import javax.swing.JFileChooser;
import ValidationRules.*;

/**
 *
 * @author nishansubba
 */
public class AddItem extends javax.swing.JPanel {

    /**
     * Creates new form AddItem
     */
    public AddItem() {
        initComponents();
        msgLabel.setVisible(false);
        loadCategoriesFromDb();
        loadLocationsFromDb();
    }
    
    public void reloadItemDropdown() {
        loadCategoriesFromDb();
        loadLocationsFromDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        itemDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        itemName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        itemNote = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        itemQuantity = new javax.swing.JSpinner();
        itemCost = new javax.swing.JSpinner();
        imageBtn = new javax.swing.JButton();
        msgLabel = new javax.swing.JLabel();
        ItemCategory = new javax.swing.JComboBox<>();
        itemLocation = new javax.swing.JComboBox<>();
        itemImageUrl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(9, 64, 103));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Item");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date*");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name*");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Location*");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Category*");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cost*");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quantity*");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Note");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Upload Image");

        cancelBtn.setBackground(new java.awt.Color(228, 77, 46));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelItemBtnClicked(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(44, 182, 125));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveItemBtnClicked(evt);
            }
        });

        imageBtn.setBackground(new java.awt.Color(255, 153, 0));
        imageBtn.setText("choose img");
        imageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadImageItemBtnClicked(evt);
            }
        });

        msgLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        msgLabel.setForeground(new java.awt.Color(255, 51, 0));
        msgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        itemImageUrl.setForeground(new java.awt.Color(255, 255, 255));
        itemImageUrl.setText("No file selected");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(itemDate, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(itemCost, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ItemCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(471, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(itemImageUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(352, 352, 352)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(itemNote, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(itemDate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(itemCost))
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(itemQuantity)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemNote, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ItemCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemImageUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveItemBtnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveItemBtnClicked
        // TODO add your handling code here:
        String message = "";
        if (itemName.getText().trim().isEmpty()) {
            message = "Item name cannot be empty!";
            System.out.println(message);
        } 
        
        
        else {
            String itemDateStr = itemDate.getText().trim();
            String itemNameStr = itemName.getText().trim();
            String locationStr = (String) itemLocation.getSelectedItem();
            String categoryStr = (String) ItemCategory.getSelectedItem();
            
            

            int locationId = Integer.parseInt(locationStr.split(" - ")[0]);
            int categoryId = Integer.parseInt(categoryStr.split(" - ")[0]);
            
            System.out.println("*********** Add Item ****************");
            System.out.println("Date: " + itemDate.getText());
            System.out.println("Name: " + itemName.getText());
            System.out.println("Location: " + locationStr);
            System.out.println("Category: " + categoryStr);
            System.out.println("Cost: " + itemCost.getValue());
            System.out.println("Quantity: " + itemQuantity.getValue());
            System.out.println("Note: " + itemNote.getText());
            System.out.println("Image url: " + itemImageUrl.getText());
            System.out.println("*************************************");
            
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("HomeBaseDesktopPU");
            EntityManager em = emf.createEntityManager();
            
            try {
                // make sure required fields: name, date, location, and category is not empty
                HomeBaseFieldRules fieldRule = new HomeBaseFieldRules();
                java.util.Map<String, String> requiredFields = new java.util.HashMap<>();
                requiredFields.put("Item date", itemDateStr);
                requiredFields.put("Item name", itemNameStr);
                requiredFields.put("Location", locationStr);
                requiredFields.put("Category", categoryStr);
                fieldRule.testRequiredField(requiredFields);

                // test the date format and make sure its not set to future
                HomeBaseDateRules dateRule = new HomeBaseDateRules();
                dateRule.testItemDate(itemDate.getText());

                // check the price and quantity
                HomeBasePriceRules priceRule = new HomeBasePriceRules();
                priceRule.testItemPrice((Integer) itemCost.getValue());

                HomeBaseQuantityRules quantityRule = new HomeBaseQuantityRules();

                quantityRule.testItemQuantity((Integer) itemQuantity.getValue());

                Item item = new Item();
                item.setDate(itemDate.getText());
                item.setName(itemName.getText());
                
                Location location = em.find(Location.class, locationId);
                Category category = em.find(Category.class, categoryId);
                
                item.setLocationId(location);
                item.setCategoryId(category);
                item.setCost((Integer) itemCost.getValue());
                item.setQuantity((Integer) itemQuantity.getValue());
                item.setNote(itemNote.getText());
                item.setUrlPath(itemImageUrl.getText());
               
                em.getTransaction().begin();
                em.persist(item);
                em.getTransaction().commit();
                em.close();
                emf.close();

                message = "Item saved successfully!";
            } catch (Exception ex) {
                message = ex.getMessage();
            }
        }

        msgLabel.setText(message);
        msgLabel.setVisible(true);
        
        Timer timer = new Timer(5000, e -> {
            msgLabel.setVisible(false);
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_saveItemBtnClicked

    private void cancelItemBtnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelItemBtnClicked
        // TODO add your handling code here:
        itemName.setText("");
        itemDate.setText("");
        itemNote.setText("");
        itemQuantity.setValue(0);
        itemCost.setValue(0);
        itemImageUrl.setText("No file selected");
    }//GEN-LAST:event_cancelItemBtnClicked

    private void uploadImageItemBtnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadImageItemBtnClicked
        // TODO add your handling code here:
        JFileChooser browse = new JFileChooser();
        
        int result = browse.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = browse.getSelectedFile();
            itemImageUrl.setText(file.getName());
        }
    }//GEN-LAST:event_uploadImageItemBtnClicked
    
    private void loadCategoriesFromDb() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("HomeBaseDesktopPU");
        EntityManager em = emf.createEntityManager();
        
        try {
            List<Category> categories = em.createQuery("SELECT category FROM Category category", Category.class).getResultList();
            ItemCategory.removeAllItems();
            
            for (Category c : categories) {
                ItemCategory.addItem(c.getCategoryId() + " - " + c.getName());
            }
            
            em.close();
            emf.close();
        } catch (Exception ex) {
            System.out.println("Error loading categories in Item form");
        } 
    }
    
    private void loadLocationsFromDb() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("HomeBaseDesktopPU");
        EntityManager em = emf.createEntityManager();
        
        try {
            List<Location> locations = em.createQuery("SELECT location FROM Location location", Location.class).getResultList();
            itemLocation.removeAllItems();
            
            for (Location location : locations) {
                itemLocation.addItem(location.getLocationId() + " - " + location.getName());
            }
            
            em.close();
            emf.close();
        } catch (Exception ex) {
            System.out.println("Error loading location in Item form");
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ItemCategory;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton imageBtn;
    private javax.swing.JSpinner itemCost;
    private javax.swing.JTextField itemDate;
    private javax.swing.JLabel itemImageUrl;
    private javax.swing.JComboBox<String> itemLocation;
    private javax.swing.JTextField itemName;
    private javax.swing.JTextField itemNote;
    private javax.swing.JSpinner itemQuantity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
