package homebasedesktop;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import homebasedesktop.entity.*;
import javax.persistence.*;
import javax.swing.Timer;
import ValidationRules.*;
import java.util.List;
/**
 *
 * @author nishansubba
 */
public class AddLocation extends javax.swing.JPanel {

    /**
     * Creates new form AddLocation
     */
    public AddLocation() {
        initComponents();
        msgLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locationName = new javax.swing.JTextField();
        locationNote = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        msgLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(9, 64, 103));

        locationNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationNoteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Note");

        cancelBtn.setBackground(new java.awt.Color(228, 77, 46));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelLocationBtnCicked(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(44, 182, 125));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveLocationBtn(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Location");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name*");

        msgLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        msgLabel.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(locationNote, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(locationName, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(609, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationName, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationNote, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveLocationBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveLocationBtn
        // TODO add your handling code here:
        String message = "";
        if (locationName.getText().trim().isEmpty()) {
            message = "Location name cannot be empty!";
            System.out.println(message);
        } else { 
            System.out.println("*********** Add Location ****************");
            System.out.println("Location Name: " + locationName.getText());
            System.out.println("Location Note: " + locationNote.getText());
            System.out.println("*************************************");

            try {
                EntityManagerFactory emf = Persistence.createEntityManagerFactory("HomeBaseDesktopPU");
                EntityManager em = emf.createEntityManager();
          
                List<String> usedLocationNames = em.createQuery("SELECT location.name FROM Location location", String.class).getResultList();
                HomeBaseNameRules nameRule = new HomeBaseNameRules();
                nameRule.testUniqueNameForCategoryLocation(locationName.getText(), usedLocationNames);

                Location location = new Location();
                location.setName(locationName.getText());
                location.setNote(locationNote.getText());

                
                em.getTransaction().begin();
                em.persist(location);
                em.getTransaction().commit();
                em.close();
                emf.close();

                message = "Location saved successfully!";
            } catch (Exception ex) {
                message = ex.getMessage();
            }
        }

        msgLabel.setText(message);
        msgLabel.setVisible(true);
        
        Timer timer = new Timer(5000, e -> {
            msgLabel.setVisible(false);
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_saveLocationBtn

    private void locationNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationNoteActionPerformed

    private void cancelLocationBtnCicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelLocationBtnCicked
        // TODO add your handling code here:
        locationName.setText("");
        locationNote.setText("");
    }//GEN-LAST:event_cancelLocationBtnCicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField locationName;
    private javax.swing.JTextField locationNote;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
