/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package homebasedesktop;

import homebasedesktop.entity.*;
import javax.persistence.*;
import javax.swing.Timer;
/**
 *
 * @author nishansubba
 */
public class DeleteData extends javax.swing.JPanel {

    /**
     * Creates new form DeleteData
     */
    public DeleteData() {
        initComponents();
        msgLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tableField = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        idField = new javax.swing.JSpinner();
        msgLabel = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(9, 64, 103));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delete Data");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Table");

        tableField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - Category", "2 - Location", "3 - Item", "4 - Wishlist" }));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter ID");

        msgLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        msgLabel.setForeground(new java.awt.Color(255, 51, 0));

        deleteBtn.setBackground(new java.awt.Color(228, 77, 46));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDeleteBtnClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tableField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(689, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dataDeleteBtnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDeleteBtnClicked
        // TODO add your handling code here:
        String message = "";

        String selectedTable = (String) tableField.getSelectedItem();
        int tableIndex = Integer.parseInt(selectedTable.substring(0,1));
        int itemId = (Integer) idField.getValue();

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("HomeBaseDesktopPU");
        EntityManager em = emf.createEntityManager();

        try {

            em.getTransaction().begin();

            switch (tableIndex) {
                case 1:
                    Category category = em.find(Category.class, itemId);
                    if (category != null) {
                    em.remove(category);
                    message = "Category deleted successfully";
                    } else {
                    message = "Category ID does not exist.";
                    }
                    break;
                case 2:
                    Location location = em.find(Location.class, itemId);
                    if (location != null) {
                    em.remove(location);
                    message = "Location deleted successfully";
                    } else {
                    message = "Location ID does not exist.";
                    }
                    break;
                case 3:
                    Item item = em.find(Item.class, itemId);
                    if (item != null) {
                    em.remove(item);
                    message = "Item deleted successfully";
                    } else {
                    message = "Item ID does not exist.";
                    }
                    break;
                case 4:
                    Wishlist wishlist = em.find(Wishlist.class, itemId);
                    if (wishlist != null) {
                    em.remove(wishlist);
                    message = "Wishlist deleted successfully";
                    } else {
                    message = "Wishlist ID does not exist.";
                    }
                    break;
                default:
                message = "Invalid table, please try again";
                break;
            }
            em.getTransaction().commit();
        }
        catch (Exception ex) {
            message = ex.getMessage();
        }
        msgLabel.setText(message);
        msgLabel.setVisible(true);
        
        Timer timer = new Timer(5000, e -> {
            msgLabel.setVisible(false);
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_dataDeleteBtnClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JSpinner idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JComboBox<String> tableField;
    // End of variables declaration//GEN-END:variables
}
