package homebasedesktop;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.CardLayout;
import javax.swing.JScrollPane;
/**
 *
 * @author nishansubba
 */
public class HomePage extends javax.swing.JFrame {
    private AddItem addItemPanel;
    private ViewData viewDataPanel;
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        contentPanel.add(new Dashboard(), "Dashboard");
        addItemPanel = new AddItem();
        contentPanel.add(addItemPanel, "AddItem");
        contentPanel.add(new AddLocation(), "AddLocation");
        contentPanel.add(new AddCategory(), "AddCategory");
        contentPanel.add(new AddWishlist(), "AddWishlist");
//        viewDataPanel = new ViewData();
//        contentPanel.add(viewDataPanel, "ViewData");
        viewDataPanel = new ViewData();

        JScrollPane scrollPane = new JScrollPane(viewDataPanel);
        scrollPane.getVerticalScrollBar().setUnitIncrement(16); // smooth scroll

        contentPanel.add(scrollPane, "ViewData");
        contentPanel.add(new DeleteData(), "DeleteData");
        CardLayout cardLayout = (CardLayout) contentPanel.getLayout();
        cardLayout.show(contentPanel, "Dashboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navMenu = new javax.swing.JPanel();
        dashboardBtn = new javax.swing.JButton();
        addItemBtn = new javax.swing.JButton();
        addCategoryBtn = new javax.swing.JButton();
        addLocationBtn = new javax.swing.JButton();
        addWishlistBtn = new javax.swing.JButton();
        viewDataBtn = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        viewDataBtn1 = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 238, 239));

        navMenu.setBackground(new java.awt.Color(255, 142, 60));

        dashboardBtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        dashboardBtn.setText("Dashboard");
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnClicked(evt);
            }
        });

        addItemBtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        addItemBtn.setText("Add Item");
        addItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemBtnClicked(evt);
            }
        });

        addCategoryBtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        addCategoryBtn.setText("Add Category");
        addCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoryBtnClicked(evt);
            }
        });

        addLocationBtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        addLocationBtn.setText("Add Location");
        addLocationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLocationBtnClicked(evt);
            }
        });

        addWishlistBtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        addWishlistBtn.setText("Add Wishlist");
        addWishlistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWishlistBtnClicked(evt);
            }
        });

        viewDataBtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        viewDataBtn.setText("View Data");
        viewDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDataBtnClicked(evt);
            }
        });

        logoLabel.setBackground(new java.awt.Color(0, 204, 153));
        logoLabel.setFont(new java.awt.Font("Lucida Grande", 3, 36)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setText("HomeBase");

        viewDataBtn1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        viewDataBtn1.setText("Delete Data");
        viewDataBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDeleteBtnClicked(evt);
            }
        });

        javax.swing.GroupLayout navMenuLayout = new javax.swing.GroupLayout(navMenu);
        navMenu.setLayout(navMenuLayout);
        navMenuLayout.setHorizontalGroup(
            navMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navMenuLayout.createSequentialGroup()
                .addGroup(navMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(navMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dashboardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addItemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(addCategoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(addLocationBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(addWishlistBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(viewDataBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(viewDataBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)))
                    .addGroup(navMenuLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        navMenuLayout.setVerticalGroup(
            navMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navMenuLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addLocationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addWishlistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewDataBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(9, 64, 103));
        contentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBtnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) contentPanel.getLayout();
        cardLayout.show(contentPanel, "Dashboard");
    }//GEN-LAST:event_dashboardBtnClicked

    private void addItemBtnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBtnClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) contentPanel.getLayout();
        addItemPanel.reloadItemDropdown();
        cardLayout.show(contentPanel, "AddItem");
    }//GEN-LAST:event_addItemBtnClicked

    private void addCategoryBtnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategoryBtnClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) contentPanel.getLayout();
        cardLayout.show(contentPanel, "AddCategory");
    }//GEN-LAST:event_addCategoryBtnClicked

    private void addLocationBtnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLocationBtnClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) contentPanel.getLayout();
        cardLayout.show(contentPanel, "AddLocation");
    }//GEN-LAST:event_addLocationBtnClicked

    private void addWishlistBtnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWishlistBtnClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) contentPanel.getLayout();
        cardLayout.show(contentPanel, "AddWishlist");
    }//GEN-LAST:event_addWishlistBtnClicked

    private void viewDataBtnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDataBtnClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) contentPanel.getLayout();
        viewDataPanel.reloadViewDate();
        cardLayout.show(contentPanel, "ViewData");
    }//GEN-LAST:event_viewDataBtnClicked

    private void viewDeleteBtnClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDeleteBtnClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) contentPanel.getLayout();
        cardLayout.show(contentPanel, "DeleteData");
    }//GEN-LAST:event_viewDeleteBtnClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCategoryBtn;
    private javax.swing.JButton addItemBtn;
    private javax.swing.JButton addLocationBtn;
    private javax.swing.JButton addWishlistBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel navMenu;
    private javax.swing.JButton viewDataBtn;
    private javax.swing.JButton viewDataBtn1;
    // End of variables declaration//GEN-END:variables
}
